version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_app
    entrypoint: >
      sh -c "
      echo 'Waiting for database...' &&
      sleep 3;
      echo 'Applying migrations...' &&
      export PYTHONPATH=/app &&
      alembic upgrade head &&
      echo 'Starting FastAPI...' &&
      exec uvicorn main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      PYTHONPATH: /app
    depends_on:
      - db
    volumes:
      - ./src:/app
      - ./alembic.ini:/app/alembic.ini
      - ./src/media:/app/media

volumes:
  postgres_data:
