from abc import ABC, abstractmethod
from typing import Generic, List, Type, TypeVar, overload
from uuid import UUID

from application.common.dtos import PagedResult, Result
from domain.entities import IBaseAuditableEntity, Profile, User


T = TypeVar("T", bound="IBaseAuditableEntity")

class IGenericRepository(ABC, Generic[T]):
    @abstractmethod
    async def get_by_id_async(self, id: UUID) -> Result[T]: ...
    @abstractmethod
    async def get_all_async(self) -> Result[List[T]]: ...
    @abstractmethod
    async def get_page_async(self, page: int, size: int) -> PagedResult[T]: ...
    @abstractmethod
    async def add_async(self, entity: T) -> Result[UUID]: ...
    @abstractmethod
    async def update_async(self, entity: T) -> Result[None]: ...
    @abstractmethod
    async def delete_async(self, id: UUID) -> Result[None]: ...


class IUserRepository(IGenericRepository[User], ABC):
    @abstractmethod
    async def find_by_email_async(self, email: str) -> Result[User]: ...


class IProfileRepository(IGenericRepository[Profile], ABC):
    @abstractmethod
    async def get_by_user_async(self, user_id: UUID) -> Result[Profile]: ...


class IUnitOfWork(ABC):
    @abstractmethod
    async def __aenter__(self) -> "IUnitOfWork": ...
    @abstractmethod
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    @abstractmethod
    async def save_async(self) -> int: ...
    @abstractmethod
    async def rollback_async(self) -> None: ...
    @overload
    def repository(self, entity_cls: Type[User]) -> IUserRepository: ...
    @overload
    def repository(self, entity_cls: Type[Profile]) -> IProfileRepository: ...
    @overload
    def repository(self, entity_cls: Type[T]) -> IGenericRepository[T]: ...
    @abstractmethod
    def repository(self, entity_cls: Type[T]) -> "IGenericRepository[T]": ...